import 'bootstrap/dist/css/bootstrap.min.css';
import PropTypes from 'prop-types';
import { ContactsProvider } from './contexts/contactsContext';
import BootstrapClient from './components/BootstrapClient';

export const metadata = {
  title: 'Contact List Project',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <BootstrapClient />
      <ContactsProvider>
        <body className="bg-dark-subtle">{children}</body>
      </ContactsProvider>
    </html>
  );
}

RootLayout.propTypes = {
  children: PropTypes.object,
};
