import { Inter } from 'next/font/google';
import './globals.css';
import PropTypes from 'prop-types';
import { ContactsProvider } from './contexts/contactsContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ContactsProvider>
        <body className={inter.className}>{children}</body>
      </ContactsProvider>
    </html>
  );
}

RootLayout.propTypes = {
  children: PropTypes.object,
};
